services:
  cns:
    restEndpoint: '${CERC_REGISTRY_REST_ENDPOINT:-https://laconicd.laconic.com}'
    gqlEndpoint: '${CERC_REGISTRY_GQL_ENDPOINT:-https://laconicd.laconic.com/api}'
    chainId: laconic_9000-1
    gas: 9950000
    fees: 15000000alnt